[[redirects]]
  from = "/docs/start.html"
  to = "https://docs.openzeppelin.com/sdk/"
  status = 301

[[redirects]]
  from = "/docs/apis.html"
  to = "https://docs.openzeppelin.com/sdk/"
  status = 301

[[redirects]]
  from = "/docs/*"
  to = "https://docs.openzeppelin.com/sdk/:splat"
  status = 301

[[redirects]]
  from = "/"
  to = "https://docs.openzeppelin.com/sdk/"
  status = 301
